version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: refref-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: refref
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  admin:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: refref-admin
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/refref
      BETTER_AUTH_SECRET: ${BETTER_AUTH_SECRET:-your-secret-key-change-in-production}
      BETTER_AUTH_URL: ${BETTER_AUTH_URL:-http://localhost:3000}
      NEXT_PUBLIC_APP_URL: ${NEXT_PUBLIC_APP_URL:-http://localhost:3000}
      RESEND_API_KEY: ${RESEND_API_KEY:-test_key}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID:-}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET:-}
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./apps/admin/.env:/app/apps/admin/.env
    command: >
      sh -c "
        cd apps/admin &&
        pnpm -F @refref/coredb db:push &&
        pnpm -F @refref/coredb db:seed &&
        pnpm start
      "

volumes:
  postgres_data: